[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
format="on [$branch]($style) "

[git_status]
format='([$all_status$ahead_behind]($style) )'
ahead="↑"
behind="↓"
deleted="x"
modified="*"
